openapi: 3.0.3
info:
  version: 1.0.0
  title: Universal Credit Liability
  description: |-
    # Usage Terms
    These interfaces are business-critical interfaces for HMRC and DWP, supporting thousands of staff - all consumption, or change in consumption levels, should be registered and fully approved (see Registered Consumers below).
  contact: {}
  license:
    name: HMRC
    url: https://license.example.hmrc.gov.uk
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
tags: []
paths:
  /misc/universal-credit/liability/notification:
    post:
      summary: Universal Credit Liability Notification
      description: |-
        # Purpose
        This API provides the capability for DWP to send Universal Credit Liability notifications for a given individual on NPS (National Insurance & PAYE Service).
      security:
        - applicationRestricted: [ write:universal-credit-liability-notification ]
      operationId: postUniversalCreditLiabilityDetails
      parameters:
        - $ref: '#/components/parameters/correlationId'
        - $ref: '#/components/parameters/govUkOriginatorId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUniversalCreditLiabilityRequest'
            examples:
              populatedRequest:
                value:
                  universalCreditLiabilityDetail:
                    nationalInsuranceNumber: "AA123456"
                    universalCreditRecordType: "LCW/LCWRA"
                    universalCreditAction: "Insert"
                    dateOfBirth: '2002-10-10'
                    liabilityStartDate: '2015-08-19'
                    liabilityEndDate: '2025-01-04'
      responses:
        '204':
          description: Successful - No Content
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
        '400':
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse_400'
              examples:
                Actual_Response:
                  value:
                    code: "BAD_REQUEST"
                    message: "Bad Request"
                    errors:
                      - code: '400.2'
                        message: HTTP message not readable
                      - code: '400.1'
                        message: "Constraint Violation - Invalid/Missing input parameter: <parameter>"
          description: Bad Request
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
        '403':
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse_403'
              examples:
                Forbidden_Response:
                  value:
                    code: "FORBIDDEN"
                    message: "Forbidden"
                    errors:
                      - code: '403.2'
                        message: Forbidden
          description: 'Forbidden'
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
        '404':
          description: Not Found Response
          $ref: '#/components/responses/notFoundErrorResponse'
        '422':
          description: Unprocessable Entity
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/errorResponse_422'
              examples:
                422_StartDateBefore29042013:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65536"
                        message: 'Start date before 29/04/2013'
                422_EndDateBeforeStartDate:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65537"
                        message: 'End date before start date'
                422_EndDateMissingTermination:
                  value:
                    failures:
                      - reason: 'End date missing but the input was a Termination'
                        code: "65538"
                422_UCS2PStartDateAfter05042016:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65539"
                        message: 'UC (S2P) Start Date after 05/04/2016'
                422_UCS2PEndDateAfter05042016:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65540"
                        message: 'UC (S2P) End Date after 05/04/2016'
                422_PseudoAccount:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65541"
                        message: 'The NINO input matches a Pseudo Account'
                422_NonLiveAccount:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65542"
                        message: 'The NINO input matches a non-live account (including redundant, amalgamated and administrative account types)'
                422_AccountTransferredIsleOfMan:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65543"
                        message: 'The NINO input matches an account that has been transferred to the Isle of Man'
                422_StartDateBefore16thBirthday:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "65026"
                        message: 'Start date must not be before 16th birthday'
                422_StartDateAfterSPA:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "55029"
                        message: 'Start Date later than SPA'
                422_StartDateAfterDeath:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "64996"
                        message: 'Start Date is not before date of death'
                422_EndDateAfterSPA:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "55008"
                        message: 'End Date must be earlier than State Pension Age'
                422_StartAndEndDateAfterDeath:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "55006"
                        message: 'Start Date and End Date must be earlier than Date of Death'
                422_EndDateAfterDeath:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "55027"
                        message: 'End Date later than Date of Death'
                422_ConflictingLiability:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "55038"
                        message: 'A conflicting or identical Liability is already recorded'
                422_NotWithinUCPeriod:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "64997"
                        message: 'LCW/LCWRA not within a period of UC'
                422_LCWLCWRAOverride:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "64998"
                        message: 'LCW/LCWRA Override not within a period of LCW/LCWRA'
                422_NoMatchingLiability:
                  value:
                    code: "UNPROCESSABLE_ENTITY"
                    message: "Unprocessable Entity"
                    errors:
                      - code: "55039"
                        message: 'NO corresponding liability found'
        '500':
          description: Internal Server Error Response
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes:
            write:universal-credit-liability-notification: Create new notifications for Universal Credit Liability
  headers:
    correlationId:
      required: true
      schema:
        $ref: '#/components/schemas/correlationId'
  parameters:
    correlationId:
      description:
        Correlation ID - used for traceability purposes - note that this
        value in the response matches that received in the request to allow correlation.
      in: header
      name: correlationId
      required: true
      schema:
        $ref: '#/components/schemas/correlationId'
    govUkOriginatorId:
      description: Identity of the Originating System that made the API call.
      in: header
      name: gov-uk-originator-id
      required: true
      schema:
        $ref: '#/components/schemas/govUkOriginatorId'
  responses:
    internalServerErrorResponse:
      description: Internal Server Error
      headers:
        correlationId:
          $ref: '#/components/headers/correlationId'
    notFoundErrorResponse:
      headers:
        correlationId:
          $ref: '#/components/headers/correlationId'
      description: The requested resource could not be found
  schemas:
    correlationId:
      type: string
      description: Correlation ID - used for traceability purposes - note that this
        value in the response matches that received in the request to allow correlation.
      format: uuid
      example: e470d658-99f7-4292-a4a1-ed12c72f1337
    govUkOriginatorId:
      description: Identity of the Originating System that made the API call
      type: string
      minLength: 4
      maxLength: 40
    PostUniversalCreditLiabilityRequest:
      type: object
      required:
        - universalCreditLiabilityDetail
      properties:
        universalCreditLiabilityDetail:
          $ref: '#/components/schemas/UniversalCreditLiabilityDetail'
    UniversalCreditLiabilityDetail:
      type: object
      required:
        - nationalInsuranceNumber
        - universalCreditRecordType
        - universalCreditAction
        - dateOfBirth
        - liabilityStartDate
      properties:
        nationalInsuranceNumber:
          $ref: '#/components/schemas/nationalInsuranceNumber'
        universalCreditRecordType:
          $ref: '#/components/schemas/universalCreditRecordType'
        universalCreditAction:
          description: >-
            Indicator to determine the action to be taken.
          type: string
          enum:
            - Insert
        dateOfBirth:
          $ref: '#/components/schemas/dateOfBirth'
        liabilityStartDate:
          $ref: '#/components/schemas/liabilityStartDate'
        liabilityEndDate:
          $ref: '#/components/schemas/liabilityEndDate'
      description: Request body for this API.
    TerminateUniversalCreditLiability:
      type: object
      required:
        - nationalInsuranceNumber
        - universalCreditRecordType
        - universalCreditAction
        - dateOfBirth
        - liabilityStartDate
        - liabilityEndDate
      properties:
        nationalInsuranceNumber:
          $ref: '#/components/schemas/nationalInsuranceNumber'
        universalCreditRecordType:
          $ref: '#/components/schemas/universalCreditRecordType'
        universalCreditAction:
          description: >-
            Indicator to determine the action to be taken.
          type: string
          enum:
            - Terminate
        dateOfBirth:
          $ref: '#/components/schemas/dateOfBirth'
        liabilityStartDate:
          $ref: '#/components/schemas/liabilityStartDate'
        liabilityEndDate:
          $ref: '#/components/schemas/liabilityEndDate'
      description: Request body for this API.
    errorResponse_400:
      description: Array of Error Response Failure Object in Error Response.
      title: Error Response
      properties:
        code:
          type: string
          enum:
            - "BAD_REQUEST"
        message:
          type: string
          enum:
            - "Bad request"
        errors:
          items:
            $ref: '#/components/schemas/errorResourceObj_400'
          type: array
          minItems: 1
      type: object
      required:
        - code
        - message
        - errors
    errorResourceObj_400:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description:
            "The error code representing the error that has occurred. Valid values are<br/>
            400.1 - Constraint violation - 'Invalid/Missing input parameter <path.to.field>'<br/>
            400.2 - HTTP message not readable"
          type: string
          enum:
            - '400.1'
            - '400.2'
        message:
          minLength: 1
          description: Displays the reason of the failure.
          type: string
          maxLength: 120
    errorResponse_403:
      description: Array of Error Response Failure Object in Error Response.
      title: Error Response
      properties:
        code:
          type: string
          enum:
            - "FORBIDDEN"
        message:
          type: string
          enum:
            - "Forbidden"
        errors:
          items:
            $ref: '#/components/schemas/errorResourceObj_403_Forbidden'
          type: array
          minItems: 1
      type: object
      required:
        - code
        - message
        - errors
    errorResourceObj_403_Forbidden:
      title: 403_Forbidden
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: The error code representing the Forbidden Error.
          type: string
          enum:
            - "403.2"
        message:
          description: Displays the reason of the failure.
          type: string
          enum:
            - Forbidden
    errorResponse_422:
      description: Error Response Payload for this API
      title: Error Response
      type: object
      properties:
        code:
          type: string
          enum:
            - "UNPROCESSABLE_ENTITY"
        message:
          type: string
          enum:
            - "Unprocessable Entity"
        errors:
          $ref: '#/components/schemas/errorResponseFailure_422'
      required:
        - code
        - message
        - errors
    errorResponseFailure_422:
      description: Array of Error Response Failure Object in Error Response.
      title: Failure Object in Error Response
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/errorResourceObj_422'
    errorResourceObj_422:
      type: object
      required:
        - code
        - message
      properties:
        code:
          oneOf:
            - $ref: '#/components/schemas/ExistingErrorCodes'
            - $ref: '#/components/schemas/FutureExtensions'
        message:
          minLength: 1
          description: Displays the reason of the failure.
          type: string
          maxLength: 120
    ExistingErrorCodes:
      description:
        "These are all error codes that can occur at the time of writing, we do not anticipate changes in the foreseeable future.<br/>
        55006 - Start Date and End Date must be earlier than Date of Death<br>
        55008 - End Date must be earlier than State Pension Age<br>
        55027 - End Date later than Date of Death<br>
        55029 - Start Date later than SPA<br>
        55038 - A conflicting or identical Liability is already recorded<br>
        55039 - NO corresponding liability found<br>
        64996 - Start Date is not before date of death<br>
        64997 - LCW/LCWRA not within a period of UC<br>
        64998 - LCW/LCWRA Override not within a period of LCW/LCWRA<br>
        65026 - Start date must not be before 16th birthday<br>
        65536 - Start date before 29/04/2013<br>
        65537 - End date before start date<br>
        65538 - End date missing but the input was a Termination<br>
        65539 - UC (S2P) Start Date after 05/04/2016<br>
        65540 - UC (S2P) End Date after 05/04/2016<br>
        65541 - The NINO input matches a Pseudo Account<br>
        65542 - The NINO input matches a non-live account (including redundant, amalgamated and administrative account types)<br>
        65543 - The NINO input matches an account that has been transferred to the Isle of Man<br>
        "
      type: string
      enum:
        - 55006
        - 55008
        - 55027
        - 55029
        - 55038
        - 55039
        - 64996
        - 64997
        - 64998
        - 65026
        - 65536
        - 65537
        - 65539
        - 65540
        - 65541
        - 65542
        - 65543
    FutureExtensions:
      description:
        "This is reserved to allow future modifications of 422s without breaking the existing interface."
      type: string
      minLength: 1
      maxLength: 10
    universalCreditRecordType:
      $ref: '#/components/schemas/EnumUniversalCreditRecordType'
    EnumUniversalCreditRecordType:
      description: >-
        Type of record. UC, UC(S2P), LCW/LCWRA.
      enum:
        - UC
        - UC(S2P)
        - LCW/LCWRA
      type: string
    dateOfBirth:
      description: >-
        The individual's date of birth.
      type: string
      format: date
      pattern: >-
        ^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[\\-]02[\\-]29|((19|20)[0-9]{2}[\\-](0[469]|11)[\\-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[\\-](0[13578]|1[02])[\\-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[\\-]02[\\-](0[1-9]|1[0-9]|2[0-8])))$
    liabilityStartDate:
      description: >-
        Start date of Universal Credit entitlement.
      type: string
      format: date
      pattern: >-
        ^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[\\-]02[\\-]29|((19|20)[0-9]{2}[\\-](0[469]|11)[\\-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[\\-](0[13578]|1[02])[\\-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[\\-]02[\\-](0[1-9]|1[0-9]|2[0-8])))$
    liabilityEndDate:
      description: >-
        End date of Universal Credit entitlement.
      type: string
      format: date
      pattern: >-
        ^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[\\-]02[\\-]29|((19|20)[0-9]{2}[\\-](0[469]|11)[\\-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[\\-](0[13578]|1[02])[\\-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[\\-]02[\\-](0[1-9]|1[0-9]|2[0-8])))$
    nationalInsuranceNumber:
      description:
        National Insurance Number - unique for an individual - note
        not all individuals qualify to be issued with one.
      example: AA123456
      maxLength: 8
      minLength: 8
      pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}$
      type: string
